<a href="https://colab.research.google.com/github/pys07/urban_greenspaces/blob/main/ca_lstm_DI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
+# Main code
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
import matplotlib.pyplot as plt
from PIL import Image
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
# load the image
image1 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/1993_classify_final.bmp")
image2 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/2003__DI_classify_final.bmp")
image3 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/2013_DI_Classify_final.bmp")
image4 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/2023_DI_Classify_Final.bmp")

# Convert images to arrays and normalize
image1 = np.array(image1)
image2 = np.array(image2)
image3 = np.array(image3)
image4 = np.array(image4)

In [ ]:
image1.shape
image4.shape

(2073, 1821, 3)

In [ ]:
print(image4)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [ ]:
import numpy as np

def cellular_automata(image, num_iterations):
    """Implementation of a cellular automaton for 2D colored images with a rule based on the most occurred neighbor."""

    # Define the neighborhood and update rules
    def get_neighbors(img, row, col):
        """Get the 3x3 neighborhood around a point."""
        h, w, _ = img.shape
        _ = 3
        left, right = max(col - 1, 0), min(col + 2, w)
        top, bottom = max(row - 1, 0), min(row + 2, h)
        return img[top:bottom, left:right]

    def update_state(img, row, col):
        """Update the state at position (row, col) based on its neighbors."""
        neighbors = get_neighbors(img, row, col)
        counts = np.bincount(neighbors.flatten(), minlength=6)
        max_color = np.argmax(counts)
        return max_color

    # Apply the cellular automaton rule to each color channel independently
    updated_image = np.copy(image)
    for _ in range(num_iterations):
        new_image = np.empty_like(updated_image)
        for row in range(updated_image.shape[0]):
            for col in range(updated_image.shape[1]):
                new_pixel = update_state(updated_image, row, col)
                new_image[row, col] = new_pixel
        updated_image = new_image

    return updated_image

# Apply cellular automata to the images
cellular_iterations = 10  # Number of iterations for the cellular automata
cellular_image1 = cellular_automata(image1, cellular_iterations)
print(1)
cellular_image2 = cellular_automata(image2, cellular_iterations)
print(1)
cellular_image3 = cellular_automata(image3, cellular_iterations)
print(1)
cellular_image4 = cellular_automata(image4, cellular_iterations)

1
1
1


In [ ]:
print(cellular_image1)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [ ]:
cellular_image1 = np.array(image1).astype(np.float32) / 255
cellular_image2 = np.array(image2).astype(np.float32) / 255
cellular_image3 = np.array(image3).astype(np.float32) / 255
cellular_image4 = np.array(image4).astype(np.float32) / 255

In [ ]:
cellular_image1.shape

(2073, 1821, 3)

In [ ]:
pixel_combined = []

for y in range(cellular_image1.shape[0]):
    for x in range(cellular_image1.shape[1]):

        pixel_image1 = cellular_image1[y,x]
        pixel_image2 = cellular_image2[y,x]
        pixel_image3 = cellular_image3[y,x]
        pixel_image4 = cellular_image4[y,x]

        # pixel_combined.extend([pixel_image1, pixel_image2, pixel_image3])
        pixel_combined.extend([pixel_image1, pixel_image2, pixel_image3, pixel_image4])

pixel_combined = np.array(pixel_combined)

len(pixel_combined)

15099732

In [ ]:
print(pixel_combined)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 ...
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
l = len(pixel_combined)
train = pixel_combined[:int(l*0.8)]
test = pixel_combined[int(l*0.8):]

In [ ]:
# Reshape the pixel_values_array into a rolling window with a stride of 3
window_size = 3  # Number of input elements
stride = 4  # Stride between windows
output_size = 1  # Number of output elements

# Calculate the number of windows
num_windows = (train.shape[0] - window_size) // stride + 1
num_windows

3019946

In [ ]:
# Create an empty array to store the windows
features = []
labels = []


for i in range(num_windows):
    start = i * stride
    end = start + window_size
    feature = train[start:end]
    features.append(feature)
    label = train[end]
    labels.append(label)


    #if end < train.shape[0]:
     #   feature = train[start:end]
      #  label = train[end]
       # features.append(feature)
        #labels.append(label)
    #else:
    #    break

features = np.array(features)
labels = np.array(labels)

In [ ]:
features.shape

(3019946, 3, 3)

In [ ]:
labels.shape

(3019946, 3)

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(256, input_shape=(window_size, 3), return_sequences=False),
    tf.keras.layers.Dense(3)
])

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

# Train the LSTM model
model.fit(x=features, y=labels, epochs=1)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


94374/94374 ━━━━━━━━━━━━━━━━━━━━ 1038s 11ms/step - accuracy: 0.3799 - loss: 0.0016


In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 256)                 │         266,240 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 3)                   │             771 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 801,035 (3.06 MB)

 Trainable params: 267,011 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 534,024 (2.04 MB)

In [ ]:
# model.save("PM_Prediction_CALSTM_model.h5")
model.save("2023CALSTM_DI_model.h5")

In [ ]:
window_size = 3  # Number of input elements
stride = 4  # Stride between windows
output_size = 1  # Number of output elements

# Calculate the number of windows
num_windows = (test.shape[0] - window_size) // stride + 1
num_windows

In [ ]:
test.shape

In [ ]:
row_of_zeros = np.zeros((1, 3))
test = np.concatenate([test, row_of_zeros], axis=0)
test.shape

In [ ]:
features = []
labels = []

# Generate the windows
for i in range(num_windows):
    start = i * stride
    end = start + window_size
    feature = test[start:end]
    features.append(feature)
    label = test[end]
    labels.append(label)
# Convert the list of windows to a NumPy array
features = np.array(features)
labels = np.array(labels)

In [ ]:
predict_LSTM = model.predict(features)

mae = np.mean(np.abs(labels - predict_LSTM))
mse = np.mean((labels - predict_LSTM)**2)
rmse = np.sqrt(np.mean((labels - predict_LSTM)**2))

In [ ]:
print("MAE: ",mae)
print("MSE: ",mse)
print("RMSE: ",rmse)

In [ ]:
window_size = 3  # Number of input elements
stride = 4  # Stride between windows
output_size = 1  # Number of output elements

# Calculate the number of windows
num_windows = (pixel_combined.shape[0] - window_size) // stride + 1
num_windows

In [ ]:
# Create an empty array to store the windows
predict = []

# Generate the windows
for i in range(num_windows):
    start = i * stride
    end = start + window_size
    predict.append(pixel_combined[start+1:end+1])

# Convert the list of windows to a NumPy array
predict = np.array(predict)

In [ ]:
pm_2024 = model.predict(predict)

In [ ]:
image1.shape

In [ ]:
image_shape = image1.shape
restored_image = 0
restored_image = np.reshape(pm_2024, image_shape)

restored_image.shape
restored_image *=255

In [ ]:
pil_image = Image.fromarray(np.uint8(restored_image))
pil_image.save("2033DI_CALSTM(3).bmp")
pil_image.save("2033DI_CALSTM(3).tif")

pil_image

In [ ]:
pil_image.save("2023UHI_CALSTM.png")

In [ ]:
# Main code
import numpy as np
import tensorflow as tf
from PIL import Image

# Load the images
print("Loading images...")

image1 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/1993_classify_final.bmp")
image2 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/2003__DI_classify_final.bmp")
image3 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/2013_DI_Classify_final.bmp")
#image4 = Image.open(r"/content/drive/MyDrive/2024_Work/1993-23_DI_Classify_final/2023_DI_Classify_Final.bmp")


print("Images loaded.")

# Convert images to arrays and normalize
print("Converting images to arrays and normalizing...")
image1 = np.array(image1).astype(np.float32) / 255
image2 = np.array(image2).astype(np.float32) / 255
image3 = np.array(image3).astype(np.float32) / 255
# image4 = np.array(image4).astype(np.float32) / 255
print("Images converted and normalized.")

# Combine the images
print("Combining images...")
pixel_combined = []

for y in range(image1.shape[0]):
    for x in range(image1.shape[1]):
        pixel_image1 = image1[y, x]
        pixel_image2 = image2[y, x]
        pixel_image3 = image3[y, x]
        # pixel_image4 = image4[y, x]

        pixel_combined.extend([pixel_image1, pixel_image2, pixel_image3])
        # pixel_combined.extend([pixel_image1, pixel_image2, pixel_image3, pixel_image4])

pixel_combined = np.array(pixel_combined)
print("Images combined.")

# Use the entire data for training
train = pixel_combined

# Reshape the pixel_values_array into a rolling window with a stride of 3
window_size = 2  # Number of input elements
stride = 3  # Stride between windows

# Calculate the number of windows
num_windows = (train.shape[0] - window_size) // stride + 1

# Create an empty array to store the windows
print("Creating feature and label arrays...")
features = []
labels = []

for i in range(num_windows):
    start = i * stride
    end = start + window_size

    if end < train.shape[0]:
        feature = train[start:end]
        label = train[end]
        features.append(feature)
        labels.append(label)
    else:
        break

features = np.array(features)
labels = np.array(labels)
print("Feature and label arrays created.")

# Build the LSTM model
print("Building the LSTM model...")
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(256, input_shape=(window_size, 3), return_sequences=False),
    tf.keras.layers.Dense(3)
])

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
print("LSTM model built.")




In [ ]:
# Train the LSTM model
print("Training the LSTM model...")
model.fit(x=features, y=labels, epochs=15)
print("LSTM model trained.")

# Predict using the trained model
print("Predicting with the trained model...")
predict_LSTM = model.predict(features)
print("Prediction completed.")

# Calculate metrics
print("Calculating metrics...")
mae = np.mean(np.abs(labels - predict_LSTM))
mse = np.mean((labels - predict_LSTM)**2)
rmse = np.sqrt(mse)

print("MAE: ", mae)
print("MSE: ", mse)
print("RMSE: ", rmse)

# Generate predictions for the entire dataset
print("Generating predictions for the entire dataset...")
predict = []

for i in range(num_windows):
    start = i * stride
    end = start + window_size
    predict.append(pixel_combined[start+1:end+1])

predict = np.array(predict)
pm_2024 = model.predict(predict)
print("Predictions generated.")

# Reshape the predicted pixels to the original image shape
print("Reshaping predicted pixels to the original image shape...")
image_shape = image1.shape
restored_image = np.reshape(pm_2024, image_shape)
restored_image *= 255

# Save the restored image
print("Saving the restored image...")
pil_image = Image.fromarray(np.uint8(restored_image))
pil_image.save("2023DI_CALSTM.bmp")
pil_image.save("2023DI_CALSTM.tif")
print("Restored image saved.")

pil_image.show()